### ISSUE TITLE
Also inlcude disk size / memory / CPU requirements in readme

### ISSUE THREAD

**Issue by christopherreay** [grassrootseconomics/kitabu-chain#2]
Im not yet sure, but Im running the sync on a 1GB DO machine, and I believe that the client was halting with no error message on memory full. 

This might be nonsense :)
I have just set up an 8gb swap for it, and we will see what happens

**Comment by christopherreay** [comment]
So aye, I have completed syncing, and the validator is now running. Its usage / max is around 1200MB.

When memory ran out (before I created swap), the process just happily terminated and dropped to prompt without any error message 

tyty

**Comment by kamikazechaser** [comment]
A full non-validator node uses around ~200 mb when idle. A validator node does indeed consume more resources. Our docs don't reflect this yet, but the minimum going forward should be 2gb/2 vcpu/ 40gb storage.
