### ISSUE TITLE
in ethstats-client .env, what should WS_SECRET contain?

### ISSUE THREAD

**Issue by christopherreay** [grassrootseconomics/kitabu-chain#3]
in the ethstats-client section of the readme, 

there are instructions on how to fill in the `./ethstats-client/.env` file

There are two values to compelte: `INSTANCE_NAME` and `WS_SECRET`

I have assumed that `INSTANCE_NAME` can be an arbitrary value?
I have assumed that `WS_SECRET` can be an arbitrary value, since there is no information about what it should contain.

I have set the two values to be the same thing, as it occurred to me that perhaps that is what the documentation is implying.

So my .env file is
```Shell
INSTANCE_NAME=dayzee-1
RPC_HOST=http://openethereum:8545
WS_SECRET=dayzee-1
WS_SERVER=wss://stats.kitabu.grassecon.org
```

what is the correct interpretation of the rules for this value?

**Comment by kamikazechaser** [comment]
I have updated the `.env` in the commit above. Replace those values and restart the `eth-stats-client`.
