### ISSUE TITLE
So Im running the validator and the ethstats-client

### ISSUE THREAD

**Issue by christopherreay** [grassrootseconomics/kitabu-chain#4]
They both seem to be running fine.

Is there anything else I am supposed to do? 
Maybe this is relevant to #3 

![Screenshot from 2022-06-29 16-25-45](https://user-images.githubusercontent.com/239550/176476412-aa15d898-d198-4c62-a6d1-5954e63d87c2.png)
![Screenshot from 2022-06-29 16-25-39](https://user-images.githubusercontent.com/239550/176476418-7f9cb981-c41f-4b47-8e66-457c7634bb5d.png)

(I stopped the Caddy service because Im not sure what the rpc security profile is for it :) and I dont need the API since I dont know what its for yet :)) tyty

**Comment by kamikazechaser** [comment]
Solution in #3
